### ISSUE TITLE
Picoweb failure on client connection

### ISSUE THREAD

**Issue by michthom** [CurlyTaleGamesLLC/PyKiln#2]
Hi Ben
I'm really excited to get PyKiln up and running as my wife has challenged me to automate her Paragon electric kiln and this looks like the perfect project, as I'll get to learn some things along the way, and might even be able to give some help in return.

I have got the repo installed but may have messed something up in interpreting the "getting started" guide as I'm on a Mac and a MicroPython virgin...

Currently it boots, connects to wifi and appears to start the Picoweb server, but when I connect I see:

```
PyKiln
Connection successful
('172.21.230.184', '255.255.255.0', '172.21.230.1', '172.21.230.1')
Running on http://172.21.230.184:80/
INFO:picoweb:14.000 <HTTPRequest object at 3ffe6cd0> <Stream object at 3ffe7290> "GET /"
ERROR:picoweb:14.000 <HTTPRequest object at 3ffe6cd0> <Stream object at 3ffe7290> AttributeError("'dict' object has no attribute 'host'",)
Traceback (most recent call last):
  File "/lib/picoweb/__init__.py", line 206, in _handle
  File "main.py", line 30, in index
AttributeError: 'dict' object has no attribute 'host'
INFO:picoweb:14.000 <HTTPRequest object at 3ffea7b0> <Stream object at 3ffe6e80> "GET /"
ERROR:picoweb:14.000 <HTTPRequest object at 3ffea7b0> <Stream object at 3ffe6e80> AttributeError("'dict' object has no attribute 'host'",)
Traceback (most recent call last):
  File "/lib/picoweb/__init__.py", line 206, in _handle
  File "main.py", line 30, in index
AttributeError: 'dict' object has no attribute 'host'
INFO:picoweb:14.000 <HTTPRequest object at 3ffed930> <Stream object at 3ffece00> "GET /"
ERROR:picoweb:15.000 <HTTPRequest object at 3ffed930> <Stream object at 3ffece00> AttributeError("'dict' object has no attribute 'host'",)
Traceback (most recent call last):
  File "/lib/picoweb/__init__.py", line 206, in _handle
  File "main.py", line 30, in index
AttributeError: 'dict' object has no attribute 'host'
```

I worried that I might have an old picoweb so connected to the board, and ran:
```
import upip
upip.install('picoweb')
```
...which installed v1.8.2 which I believe is the latest but that didn't improve things.

Do you have any suggestions I can look at (in the meanwhile I'll ask the Interwebs...)

**Comment by michthom** [comment]
Some progress - I updated index() in main.py as follows (one line change):

```
diff --git a/src/main.py b/src/main.py
index 7997679..fd8de00 100644
--- a/src/main.py
+++ b/src/main.py
@@ -20,14 +20,13 @@ import led
 import wifi
 wifi.setup()
 
-
 app = picoweb.WebApp(__name__)
 
 @app.route("/")
 def index(req, resp):
     # redirect to "/"
     hostURL = "http://pykiln.com/pykiln/"
-    if wifi.wifi.host == "":
+    if wifi.wifi.get('host') != "":
         hostURL = "http://" + wifi.wifi.host + "/pykiln/"
     
     headers = {"Location": hostURL + "?ip=" + wifi.ip[0]}
```

So now I can get the HTTP303 redirect to pykiln.com but things then go off the rails as there's no content shown beyond the home page menu - Edit Firing Schedules, Logging and Settings all return an HTTP404 not found page?

**Comment by michthom** [comment]
Oops - make that a 2-line change, as I noticed when I set up a local server for the files on my LAN:

```
diff --git a/src/main.py b/src/main.py
index 7997679..fd8de00 100644
--- a/src/main.py
+++ b/src/main.py
@@ -20,14 +20,13 @@ import led
 import wifi
 wifi.setup()
 
-
 app = picoweb.WebApp(__name__)
 
 @app.route("/")
 def index(req, resp):
     # redirect to "/"
     hostURL = "http://pykiln.com/pykiln/"
-    if wifi.wifi.host == "":
-        hostURL = "http://" + wifi.wifi.host + "/pykiln/"
+    if wifi.wifi.get('host') != "":
+        hostURL = "http://" + wifi.wifi.get('host') + "/pykiln/"
     
     headers = {"Location": hostURL + "?ip=" + wifi.ip[0]}
```

**Comment by michthom** [comment]
I'm really confused now. If I set a value for "host" to point to a local web server, then the initial connection to PyKiln on the ESP32 is redirected to that host (as expected). But then the client starts requesting api responses from my local web server e.g. /api/temperature and /api/get-current-segment instead of sending them to PyKiln on the ESP32, seemingly ignoring the ?ip=xxx.xxx.xxx.xxx that presumably it should use to direct the API calls?

**Comment by michthom** [comment]
I've taken a step back and used the older PiKiln repository on a Pi Zero for now, but hope to return here to help test / maybe contribute to the next version.

**Comment by BenRinthLabs** [comment]
Ah I'm sorry michthom, I don't think Github notified me when you posted this, just seeing it now. Yeah this isn't a working project yet. PiKiln was closer to working solution, but that was never 100% completed either. I just finished up some projects that were taking up my time, so now I should have a little more time to work on PyKiln. Thanks!

**Comment by michthom** [comment]
Thanks for your messages Ben, and best of luck with the new phase of PyKiln

I’m going to look into both PiKiln (whose interface I preferred) and jbruce’s project also, but I’ll keep checking in on your progress and I’m not ruling out a switch in future.

I’ve pulled the parts together for the physical side, see drawing attached. I’m hoping the circuit (that I cobbled together in a simulator) works as hoped to read the mains current without needing an ADC (as I only need an on/off indication).

Best of luck with this and your other projects!
Mike Thomson
