### ISSUE TITLE
saw your reddit post[s]

### ISSUE THREAD

**Issue by jbruce12000** [CurlyTaleGamesLLC/PyKiln#3]
You were interested in collaborating like a year [or more] ago. I never received any communication from you. Maybe it went to the spam folder?

I'm the maintainer of https://github.com/jbruce12000/kiln-controller which is a fork of https://github.com/apollo-ng/picoReflow with lots of modifications. The feature list has grown over the years as has the user base. It's a pretty active community that strives to bring accurate, web based control of kilns [or anything else that heats using elements] to the masses. Companies charge like $600 for after-market solutions that are not as accurate or easy to use.

Anyway, it might be a little late, but I'm now listening.

**Comment by BenRinthLabs** [comment]
Hi jbruce12000!

Nice to connect with you. I really love what you have done with your kiln controller. When I first started programming a kiln controller I went down the same sort of system architecture you did but as I've been progressing with the project I decided to switch to an ESP32 running Micropython and really leverage the front end using Vue + GitHub Pages (and/or a local web server). The ESP32 is only responding to API requests, it doesn't serve up webpages which keep everything fast and lightweight. I like that I don't have to deal with an OS on the ESP32, also the cost is way cheaper than a Raspberry Pi.

The more I work on this project and talk to people the more I realize that not many potters are as tech savvy as us. So, to make things easier for people, I programmed a simple Python application with a GUI to flash Micropython, set up the WiFi, and copy the PyKiln files over to the ESP32. 

I want to make the wiring as simple as I can too. I'm using a pair of PCBs. One for the ESP32 to plug into, and another that is a breakout for connections at the kiln. The two circuit boards are connected using a CAT5/6 cable and communicate using I2C. The breakout PCB makes connecting elements/relays and temperature sensors/thermocouples a snap! I just made a new revision of the PCBs but want to get some feedback before I order them. I designed the PCBs in KiCad and will release the project files as well as the gerber files as open hardware too.

I still have a lot of work to do to get PyKiln to fully functional state. I'd love to collaborate if you're interested :)

Even just having another person to bounce ideas off of is useful.

Thanks!
-Ben
